# Generated by Django 3.0.3 on 2020-02-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0004_auto_20200227_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120, verbose_name='Venue Name')),
                ('Query', models.CharField(max_length=300)),
                ('Phone', models.CharField(blank=True, max_length=20, verbose_name='Contact Phone')),
                ('Email_address', models.EmailField(blank=True, max_length=254, verbose_name='Email Address')),
            ],
        ),
    ]
