# Generated by Django 3.0.3 on 2020-02-27 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0005_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
