# Generated by Django 3.0.3 on 2020-02-27 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0007_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
