# Generated by Django 3.0.3 on 2020-02-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0009_auto_20200229_2130'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LatestPost',
            new_name='Information',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='descriptions',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='youtubelink',
            new_name='youtube',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='title',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
