# Generated by Django 3.0.3 on 2020-02-29 16:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0010_auto_20200229_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=500, unique=True),
            preserve_default=False,
        ),
    ]
